### PR TITLE
Support docker-compose updates without changing config.json

### PR DESCRIPTION
**Pull request by aborderon**
Modify the config.json file in config.example.json in the docker directory to not affect the configuration after a git pull in the node-build-monitor directory.

Update README.md

### CODE REVIEW

**Comment by marcells** [comment]
Thanks for your PR. I have two remarks.

1. I think, it would make sense to add the config.json to .gitignore. Could you do this?

2. Why did you need to add the container_name property to the YAML-Files?

**Comment by aborderon** [comment]
Hello,

I thought about adding the config.json file in .gitignore but I wanted to keep an example to use. Well I agree there is always the config.json file in the app folder.

I wanted to keep a consistency with docker run --name without the use of docker-compose. But it may be more interesting to add the container_name as a parameter in the case where there are several instances of node-build-monitor to manage the containers. To see according to what you prefer.

**Comment by marcells** [comment]
Oh, I forgot, that I need the `config.json` file to automatically create the demo page https://builds.mspi.es. :-) So, that file has to be kept.

The docker image `marcells/node-build-monitor` is always up to date with the repository (and older versions via tags).

So, currently I don't see a big issue to copy the `Dockerfile`, `config.json` and `docker-compose.*.yml` to a local folder and execute it from there.

Maybe a bash script which copies these files to a desired user directory could be enough as a user friendly and simple solution. What do you think?

**Comment by aborderon** [comment]
I do not think this is the best solution to copy / paste the files outside because after a git pull it will be necessary to copying new ones.

It may be conceivable to create a git repository only for docker compose.
Example: node-build-monitor-docker-compose

Which would contain only `docker-compose.*.yml` and `config.example.json` based on node-build-monitor docker image.

Otherwise it would be necessary to think about modifying the architecture of the project in order to have the `docker-compose.*.yml` at the root of the repository like a lot of solution today. 
What do you think?

**Comment by marcells** [comment]
Okay, I see. Thanks for your input.

What do you think about that directory structure:

- `/docker-ci` (only used for the CI)
  - `Dockerfile`
  - `config.json`
- `/docker` (this is where the `README.md` points to)
  - `Dockerfile`
  - `config.example.json`
  - all `docker-compose.*.yml` files
  - .gitignore with `config.json` entry

**Comment by aborderon** [comment]
This is a good solution yes.
Do you want me to take care of this feature?

**Comment by marcells** [comment]
Yes, if you want to, you can modify your PR. I'll then update the settings in the Docker Hub and merge it. Thank you very much.

**Comment by aborderon** [comment]
It's ok for me ;)

**Comment by marcells** [comment]
Thank you! I modified the automated build settings in the docker hub.

**Pull request merged**
