### PR TITLE
Feature/bamboo service

### PR DESCRIPTION
**Pull request by simonhard**
Add Bamboo as another service.

### CODE REVIEW

**Comment by marcells** [comment]
Hi, thanks for your contribution! :+1:

I'll merge the pull request immediately after you've fixed the following things. If you have any questions or I should help you then feel free to ask me.

- There are some build issues: https://travis-ci.org/marcells/node-build-monitor/builds/222775205
- I think, that [this line](https://github.com/marcells/node-build-monitor/pull/43/files#diff-04c6e90faac2675aa89e2176d2eec7d8R312) in unnecessary.
- [Here](https://github.com/marcells/node-build-monitor/pull/43/files#diff-9f2ec81d140a5dc3f0cefb8cfcd74a53R68) It has to be called `hasWarnings`.
- The `reason` build parameter should not contain html content. Please return a static string (e.g. "build") here and revert the css changes in the themes.
- For the `requestedFor` variable you may return the author from the `results/result/changes/change`, if possible. See the Bamboo API [here](https://developer.atlassian.com/bamboodev/rest-apis/bamboo-rest-resources#BambooRESTResources-BuildService—SpecificBuildResult) or [here](https://docs.atlassian.com/bamboo/REST/5.15.5/#d2e1185).

**Comment by simonhard** [comment]
Hey, thanks for the review. I think I now fixed the points you mentioned. 
There's no possibility to differ between errors or warnings of a build. I can only check if build is successfull or not.
Best!
Simon

**Comment by marcells** [comment]
Thanks! Looks good.

I've made two more changes.
- I renamed the configuration parameter `slug` to `planKey`, cause it's a specific parameter for the build service.
- I renamed `auth_login`/`auth_password` to `username`/`password`, cause they are more general and found in the other services, which support that basic authentication.

Please let me know, if you're fine with them. Then I'll merge the pr.

**Comment by simonhard** [comment]
Great! Thanks! That's cool!

**Comment by marcells** [comment]
Here we go. Thanks for your contribution.

**Pull request merged**
