### PR TITLE
Support for adding root CA certificates

### PR DESCRIPTION
**Pull request by LeoHuckvale**
We have a GitLab instance deployed on our network with a SSL certificate signed by our internal root CA. I've managed to get node-build-monitor working for us by hacking around to insert a custom root CA into every call to the `request` module in "app/services/GitLab.js".

Would you be amenable to supporting custom CA certs in this project? If so, I'd be more than happy to make a pull request - at least to get it working with GitLab, then we can look at other services. I would probably implement it as an optional certificate path being passed in via the configuration.

### CODE REVIEW

**Comment by LeoHuckvale** [comment]
I've made an initial attempt which works for GitLab. Will have to do some research into the other services' APIs...

**Comment by LeoHuckvale** [comment]
All of the other services, except Jenkins, use `request` at the top level too, so if the general implementation makes sense, I could try to add support for these. Testing them properly would be awkward, but could probably be done with Docker containers.

**Comment by marcells** [comment]
At first: Awesome work! Your implementation including the tests looks very good.

The jenkins-api has a `init` method, which just wraps the `request.defaults` method. So, the implementation should be similar. Currently I have an open pull request and the owner doesn't react on it. I think it's time to remove it and use `request` here, too.

The current unit tests are enough. If there are issues with the certificate, then the problem is on the side of `request`.

**Comment by LeoHuckvale** [comment]
Fantastic, thank you! :)

I'm new to JavaScript, so please let me know if there's anything I could do with regards refactoring.

**Pull request merged**
