### PR TITLE
Adds Unit Tests for Drone Service & Fixes a bug in filtering

### LINKED ISSUE #219: Unit test Drone Service
The drone service is not unit tested. I think this is leading to bugs. (I keep running into a scenario where when I do not include a `branch` or `event` it does not find and builds.

### PR DESCRIPTION
**Pull request by nkringle**
Fixes #219 

Primarily tests the filtering functionality. I end up testing by accident the api uri and service configuration. through the filtering tests. I'm not checking error handling (other than I don't get errors from my mocked server).

### CODE REVIEW

**Comment by nkringle** [comment]
@marcells

**Comment by marcells** [comment]
Thank you!

**Comment by nkringle** [comment]
@marcells You're welcome! I must have only run the tests in my ide and did not run the linter. 🙈 https://github.com/marcells/node-build-monitor/pull/222

**Comment by nkringle** [comment]
@marcells when you get a chance, could you cut a patch release with this bug fix?

**Comment by marcells** [comment]
Oh, didn't see your message. A release is on the way. @nkringle

**Pull request merged**
