### PR TITLE
Added BuildBuddy Service: https://www.buddybuild.com/, simple tests, …

### PR DESCRIPTION
**Pull request by ktoley**
…and example config in config.json.  The service will take env_var for the Access Token

### CODE REVIEW

**Comment by ktoley** [comment]
Added Service for BuddyBuild CI

**Comment by marcells** [comment]
Hey @ktoley, thank you very much for your pull request.

Do you think you could move your sample from the `config.json` to the `Readme.md` (like the other plugins)? Because the intention is that everyone has a valid and working configuration, when the repository is cloned and the build monitor started.

**Comment by marcells** [comment]
And another question. Could you integrate your test so that it is executed by grunt, like the other tests?

**Comment by ktoley** [comment]
Hey sorry, this is actually my first time contributing to an open source project.
I updated the readme however I'm not sure what what you need me to do to trigger the tests with Grunt.
It looks like the Grunt file is running anything *.js in the test folder.

**Comment by marcells** [comment]
Okay. No problem. I will take a look at the tests and grunt, when I find some time, after merging the pull request. Cause currently `grunt ci` executes jshint and then mocha. With your change jshint is ignored.

Thanks for your contribution!

**Pull request merged**
