### PR TITLE
VSTS support

### PR DESCRIPTION
**Pull request by NihalSh**
The VSTS support has been added using the REST API version 2.0. I have written extensive documentation to support the code.

#105

### CODE REVIEW

**Comment by marcells** [comment]
Awesome, thank you.

But could you rename your service and the name in the documentation to 'Tfs'. That is the official configuration name of the service.

**Comment by NihalSh** [comment]
I checked the docs again. [VSTS REST API](https://www.visualstudio.com/en-us/docs/integrate/api/build/builds) suggests a different way to configure the endpoint if its needs to be compatible with both VSTS and TFS.
The `accountname` in the docs would need to change to `instance`. The following excerpt is from docs:
```
VS Team Services account ({account}.visualstudio.com) or TFS server ({server:port}).
```

**Comment by marcells** [comment]
That sounds good. We are currently using this service for the on-premise TFS. So in future we will use your implementation.

One last cosmetic thing. Could you rename the parameter `accountname` to `instance` and describe it in the README. In that way users of the build-monitor know, that they can use the service for newer on-premise TFS versions and the hosted one.

**Comment by marcells** [comment]
You are using API Version 2. That is great. After you modified the docs and I merged your PR, I'll remove the on-premise service for TFS 2015.

Product | 1.0 | 2.0 | 3.0
-- | -- | -- | --
Team Services | X | X | X
Team Foundation Server 2017 | X | X | X
Team Foundation Server 2015 | X | X | -

**Comment by NihalSh** [comment]
Alright I will make the suggested modifications and make a pull request.

**Comment by NihalSh** [comment]
I also renamed `collection` in the docs to `project` to make it more meaningful.

**Comment by marcells** [comment]
Thanks a lot for your contribution!

**Pull request merged**
