### PR TITLE
added handling for manual step in gitlab-ci config

### PR DESCRIPTION
**Pull request by Vatrax**
added handling for manual step discused in [#118]( https://github.com/marcells/node-build-monitor/issues/118)

### CODE REVIEW

**Comment by marcells** [comment]
Thanks for you PR!

Could you please fix the build issue? And why do you check the status for all jobs with `includes` and do not use the job variable?

**Comment by marcells** [comment]
Forget my question. Just saw that a build and job are different things. 😉

Please just fix the build issue. Then I'll merge it.

**Comment by Vatrax** [comment]
done ;)

**Comment by marcells** [comment]
Thanks. I did merge it. 😉

**Pull request merged**
