### PR TITLE
New VSTS plugin

### PR DESCRIPTION
**Pull request by byatis**
Here's for previewing

### CODE REVIEW

**Comment by marcells** [comment]
Hi, awesome. Thank you!

You can fully replace the old Tfs plugin with yours, cause it doesn't work anymore.

Could you make this change? Then I'll merge your PR asap.

**Comment by byatis** [comment]
Ok, now refactored and also fixed a bug with date parsing

**Comment by marcells** [comment]
Thanks a lot. I will bump a new version later this day.

**Comment by marcells** [comment]
Thanks again for your work!

The new [release](https://github.com/marcells/node-build-monitor/releases/tag/v0.9.29) is created. In a few minutes the docker image should be ready.

**Pull request merged**
