### PR TITLE
Add a CircleCI service

### PR DESCRIPTION
**Pull request by maximelebastard**
Hello there,

in addition to Drone, as we use CircleCI too I created a service for that CI provider.

It is slightly more complex as CircleCI has a concept of job (a simple task) and a concept of workflow (a sequence of tasks to execute).

As the CircleAPI only provides the job data, I had to code something to deduct the workflow statuses in order to merge multiple jobs in a single workflow build item.

### CODE REVIEW

**Comment by marcells** [comment]
Hi, thanks again. 👍

**Comment by marcells** [comment]
Had to merge the Readme.md. Everything should be fine now.

**Comment by sverhagen** [comment]
@maximelebastard, if I may ask, so long after this pull request, why is the limit initialized at 30? That seems an unusual choice, compared to how services in Node Build Monitor are implemented. Could you elaborate?

**Comment by maximelebastard** [comment]
Hi @sverhagen, yes it's been a long teim !
For what I remember, CircleCI was quite agressive on the API throttling and limits. I had to do multiple request at each update between workflows and jobs, so I tried to find a good balance for not getting throttled.
I may have changed though

**Pull request merged**
