### PR TITLE
Fix TFSRelease grouping

### PR DESCRIPTION
**Pull request by Alea81**
Hi,

Long time no see. :)

I've created a fix for the new grouping feature of TFSRelease. There where 2 problems:
- The status was never updated correctly, if the release was already in the list, meaning, none of the changes were correctly applied.
- If there are more sub environment releases under the TFS Release Definition, the last one was taken. I've rewritten the whole thing from scratch, now it's doing a group by deploymentid and a priority sort, to get the relevant status out of the sub steps of a release.

I've tested it but please also take a look.

Cheers

### CODE REVIEW

**Comment by Alea81** [comment]
@x-jokay This should fix both of the problems.

**Comment by Alea81** [comment]
Oh, and one thing: deploymentstatus.notDeployed is definitely not an error status, either it's not started, or needs to be manually deployed, but it's not a fail at all.

**Comment by Alea81** [comment]
Have also a question to this [line](https://github.com/marcells/node-build-monitor/blob/8bbc69de25c6bde6e580ba1aa716764e29721404/app/monitor.js#L12)
Why are you using it like this and not simply use `build.etag = require("etag")(JSON.stringify(build))`, since the package.json has already getting the package. Why does it make sence to create an md5 hash?

**Comment by x-jokay** [comment]
Tested and LGTM.

**Comment by marcells** [comment]
Thank you. :smile:

**Comment by Alea81** [comment]
If you have time, could you hit the release button for these 3 PRs? :)
Would love to have these features.
Thank you. :)

**Pull request merged**
